export const FETCH_EQUIPMENT_LIST = 'FETCH_EQUIPMENT_LIST';
export const FETCH_EQUIPMENT_LIST_SUCCESS = 'FETCH_EQUIPMENT_LIST_SUCCESS';
export const FETCH_EQUIPMENT_LIST_FAIL = 'FETCH_EQUIPMENT_LIST_FAIL';

export const CREATE_EQUIPMENT = 'CREATE_EQUIPMENT';
export const CREATE_EQUIPMENT_SUCCESS = 'CREATE_EQUIPMENT_SUCCESS';
export const CREATE_EQUIPMENT_FAIL = 'CREATE_EQUIPMENT_FAIL';
