export const FETCH_HOTEL_LIST = 'FETCH_HOTEL_LIST';
export const FETCH_HOTEL_LIST_SUCCESS = 'FETCH_HOTEL_LIST_SUCCESS';
export const FETCH_HOTEL_LIST_FAIL = 'FETCH_HOTEL_LIST_FAIL';

export const SET_HOTEL_EDITING = 'SET_HOTEL_EDITING';

export const ADD_HOTEL = 'ADD_HOTEL';
export const ADD_HOTEL_SUCCESS = 'ADD_HOTEL_SUCCESS';
export const ADD_HOTEL_FAIL = 'ADD_HOTEL_FAIL';

export const EDIT_HOTEL = 'EDIT_HOTEL';
export const EDIT_HOTEL_SUCCESS = 'EDIT_HOTEL_SUCCESS';
export const EDIT_HOTEL_FAIL = 'EDIT_HOTEL_FAIL';

export const DELETE_HOTEL = 'DELETE_HOTEL';
export const DELETE_HOTEL_SUCCESS = 'DELETE_HOTEL_SUCCESS';
export const DELETE_HOTEL_FAIL = 'DELETE_HOTEL_FAIL';

export const FILTER_HOTEL = 'FILTER_HOTEL';
export const FILTER_HOTEL_SUCCESS = 'FILTER_HOTEL_SUCCESS';
export const FILTER_HOTEL_FAIL = 'FILTER_HOTEL_FAIL';

export const GET_HOTEL_BY_ID = 'GET_HOTEL_BY_ID';
export const GET_HOTEL_BY_ID_SUCCESS = 'GET_HOTEL_BY_ID_SUCCESS';
export const GET_HOTEL_BY_ID_FAIL = 'GET_HOTEL_BY_ID_FAIL';
