export const GET_CITY_LIST = 'GET_CITY_LIST';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_LIST_FAIL = 'GET_CITY_LIST_FAIL';

export const SET_CITY = 'SET_CITY';
export const SET_DISTRICT = 'SET_DISTRICT';
export const SET_WARD = 'SET_WARD';

export const GET_DISTRICT_LIST = 'GET_DISTRICT';
export const GET_DISTRICT_LIST_SUCCESS = 'GET_DISTRICT_SUCCESS';
export const GET_DISTRICT_LIST_FAIL = 'GET_DISTRICT_FAIL';

export const GET_WARD_LIST = 'GET_WARD';
export const GET_WARD_LIST_SUCCESS = 'GET_WARD_SUCCESS';
export const GET_WARD_LIST_FAIL = 'GET_WARD_FAIL';
