export const FETCH_ROOM_LIST = 'FETCH_ROOM_LIST';
export const FETCH_ROOM_LIST_SUCCESS = 'FETCH_ROOM_LIST_SUCCESS';
export const FETCH_ROOM_LIST_FAIL = 'FETCH_ROOM_LIST_FAILD';

export const SET_ROOM_EDITING = 'SET_ROOM_EDITING';

export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL';

export const EDIT_ROOM = 'EDIT_ROOM';
export const EDIT_ROOM_SUCCESS = 'EDIT_ROOM_SUCCESS';
export const EDIT_ROOM_FAIL = 'EDIT_ROOM_FAIL';

export const DELETE_ROOM = 'DELETE_ROOM';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';

export const GET_ROOM_BY_ID = 'GET_ROOM_BY_ID';
export const GET_ROOM_BY_ID_SUCCESS = 'GET_ROOM_BY_ID_SUCCESS';
export const GET_ROOM_BY_ID_FAIL = 'GET_ROOM_BY_ID_FAIL';
