export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL';

export const GET_TRANSACTION_USER = 'GET_TRANSACTION_USER';
export const GET_TRANSACTION_USER_SUCCESS = 'GET_TRANSACTION_USER_SUCCESS';
export const GET_TRANSACTION_USER_FAIL = 'GET_TRANSACTION_USER_FAIL';

export const GET_TRANSACTION_HOTEL = 'GET_TRANSACTION_HOTEL';
export const GET_TRANSACTION_HOTEL_SUCCESS = 'GET_TRANSACTION_HOTEL_SUCCESS';
export const GET_TRANSACTION_HOTEL_FAIL = 'GET_TRANSACTION_HOTEL_FAIL';

export const CHECK_IN = 'CHECK_IN';
export const CHECK_IN_SUCCESS = 'CHECK_IN_SUCCESS';
export const CHECK_IN_FAIL = 'CHECK_IN_FAIL';

export const CHECK_OUT = 'CHECK_OUT';
export const CHECK_OUT_SUCCESS = 'CHECK_OUT_SUCCESS';
export const CHECK_OUT_FAIL = 'CHECK_OUT_FAIL';
