export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAIL = 'FETCH_USER_LIST_FAIL';

export const SET_ROLE_USER = 'SET_ROLE_USER';
export const SET_ROLE_USER_SUCCESS = 'SET_ROLE_USER_SUCCESS';
export const SET_ROLE_USER_FAIL = 'SET_ROLE_USER_FAIL';
